# Generated by Django 6.0.6 on 2026-06-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('age_group', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('trip_purpose', models.CharField(max_length=50)),
                ('transport_mode', models.CharField(max_length=50)),
                ('travel_time', models.CharField(max_length=50)),
                ('travel_cost', models.CharField(max_length=50)),
                ('safety_level', models.CharField(max_length=50)),
                ('experienced_harassment', models.CharField(max_length=10)),
                ('harassment_type', models.CharField(blank=True, max_length=50)),
                ('unsafe_time', models.CharField(max_length=50)),
                ('unsafe_location', models.CharField(max_length=100)),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
